import { Contact, Message, Campaign, Template, Activity, ChartData, DashboardStats } from '@/types';

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    phone: '+1 (555) 123-4567',
    email: 'sarah.johnson@email.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    tags: ['VIP', 'Customer'],
    status: 'active',
    lastMessage: 'Thanks for the update!',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5),
    unreadCount: 2,
  },
  {
    id: '2',
    name: 'Michael Chen',
    phone: '+1 (555) 234-5678',
    email: 'michael.chen@email.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    tags: ['Lead'],
    status: 'active',
    lastMessage: 'When will my order arrive?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    unreadCount: 0,
  },
  {
    id: '3',
    name: 'Emily Davis',
    phone: '+1 (555) 345-6789',
    email: 'emily.davis@email.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    tags: ['Customer', 'Newsletter'],
    status: 'active',
    lastMessage: 'I love your products!',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unreadCount: 1,
  },
  {
    id: '4',
    name: 'David Wilson',
    phone: '+1 (555) 456-7890',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    tags: ['Prospect'],
    status: 'inactive',
    lastMessage: 'Please send me more information',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unreadCount: 0,
  },
  {
    id: '5',
    name: 'Jessica Martinez',
    phone: '+1 (555) 567-8901',
    email: 'jessica.m@email.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
    tags: ['VIP', 'Customer'],
    status: 'active',
    lastMessage: 'Can we schedule a call?',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    unreadCount: 3,
  },
  {
    id: '6',
    name: 'Robert Brown',
    phone: '+1 (555) 678-9012',
    tags: ['Lead'],
    status: 'active',
    lastMessage: 'Interested in the premium plan',
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 5),
    unreadCount: 0,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    contactId: '1',
    content: 'Hi! I wanted to check on my recent order.',
    type: 'text',
    direction: 'in',
    status: 'read',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'm2',
    contactId: '1',
    content: 'Hello Sarah! Your order #12345 is on its way. Expected delivery is tomorrow.',
    type: 'text',
    direction: 'out',
    status: 'read',
    timestamp: new Date(Date.now() - 1000 * 60 * 55),
  },
  {
    id: 'm3',
    contactId: '1',
    content: 'That\'s great news! Can you send me the tracking link?',
    type: 'text',
    direction: 'in',
    status: 'read',
    timestamp: new Date(Date.now() - 1000 * 60 * 50),
  },
  {
    id: 'm4',
    contactId: '1',
    content: 'Of course! Here\'s your tracking link: https://track.shipping.com/12345',
    type: 'text',
    direction: 'out',
    status: 'delivered',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    id: 'm5',
    contactId: '1',
    content: 'Thanks for the update!',
    type: 'text',
    direction: 'in',
    status: 'read',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Holiday Sale 2024',
    status: 'completed',
    templateId: 't1',
    templateName: 'holiday_promo',
    totalContacts: 1500,
    sent: 1500,
    delivered: 1450,
    read: 1200,
    failed: 50,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
  },
  {
    id: 'c2',
    name: 'Product Launch',
    status: 'running',
    templateId: 't2',
    templateName: 'new_product',
    totalContacts: 2000,
    sent: 1200,
    delivered: 1150,
    read: 800,
    failed: 30,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
  },
  {
    id: 'c3',
    name: 'Customer Feedback Survey',
    status: 'scheduled',
    templateId: 't3',
    templateName: 'feedback_request',
    totalContacts: 500,
    sent: 0,
    delivered: 0,
    read: 0,
    failed: 0,
    createdAt: new Date(),
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 24),
  },
  {
    id: 'c4',
    name: 'Welcome Series',
    status: 'draft',
    templateId: 't4',
    templateName: 'welcome_message',
    totalContacts: 0,
    sent: 0,
    delivered: 0,
    read: 0,
    failed: 0,
    createdAt: new Date(),
  },
];

export const mockTemplates: Template[] = [
  {
    id: 't1',
    name: 'holiday_promo',
    category: 'marketing',
    language: 'en',
    status: 'approved',
    content: 'Hi {{1}}! 🎄 Our biggest sale of the year is here! Get up to {{2}}% off on all products. Use code: {{3}}. Shop now!',
    parameters: ['name', 'discount', 'code'],
    headerType: 'image',
    headerContent: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400',
    buttons: [
      { type: 'url', text: 'Shop Now', url: 'https://shop.example.com' },
    ],
  },
  {
    id: 't2',
    name: 'new_product',
    category: 'marketing',
    language: 'en',
    status: 'approved',
    content: 'Hey {{1}}! 🚀 Introducing our latest product: {{2}}. Be among the first to try it! Limited stock available.',
    parameters: ['name', 'product_name'],
    headerType: 'image',
    headerContent: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    buttons: [
      { type: 'url', text: 'Learn More', url: 'https://example.com/product' },
      { type: 'quick_reply', text: 'Notify Me' },
    ],
  },
  {
    id: 't3',
    name: 'feedback_request',
    category: 'utility',
    language: 'en',
    status: 'approved',
    content: 'Hi {{1}}, we value your opinion! Could you take 2 minutes to share your feedback about your recent purchase? Your input helps us improve.',
    parameters: ['name'],
    buttons: [
      { type: 'url', text: 'Give Feedback', url: 'https://feedback.example.com' },
    ],
  },
  {
    id: 't4',
    name: 'welcome_message',
    category: 'utility',
    language: 'en',
    status: 'approved',
    content: 'Welcome to {{1}}, {{2}}! 👋 We\'re thrilled to have you. Here\'s what you can expect from us...',
    parameters: ['company_name', 'customer_name'],
    footerText: 'Reply STOP to unsubscribe',
  },
  {
    id: 't5',
    name: 'order_confirmation',
    category: 'utility',
    language: 'en',
    status: 'approved',
    content: 'Order Confirmed! 📦\n\nHi {{1}}, your order #{{2}} has been confirmed.\n\nTotal: ${{3}}\nEstimated Delivery: {{4}}',
    parameters: ['name', 'order_id', 'total', 'delivery_date'],
    buttons: [
      { type: 'url', text: 'Track Order', url: 'https://track.example.com' },
    ],
  },
  {
    id: 't6',
    name: 'otp_verification',
    category: 'authentication',
    language: 'en',
    status: 'approved',
    content: 'Your verification code is: {{1}}. This code expires in 10 minutes. Do not share this code with anyone.',
    parameters: ['otp_code'],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalContacts: 12458,
  activeChats: 847,
  totalCampaigns: 24,
  messagesSent: 45892,
  deliveryRate: 96.8,
  readRate: 78.5,
};

export const mockChartData: ChartData[] = [
  { name: 'Mon', sent: 1200, delivered: 1150, read: 980 },
  { name: 'Tue', sent: 1400, delivered: 1380, read: 1100 },
  { name: 'Wed', sent: 1100, delivered: 1050, read: 890 },
  { name: 'Thu', sent: 1600, delivered: 1550, read: 1300 },
  { name: 'Fri', sent: 1800, delivered: 1750, read: 1450 },
  { name: 'Sat', sent: 900, delivered: 870, read: 720 },
  { name: 'Sun', sent: 600, delivered: 580, read: 490 },
];

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    type: 'message',
    title: 'New message received',
    description: 'Sarah Johnson sent a new message',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'a2',
    type: 'campaign',
    title: 'Campaign completed',
    description: 'Holiday Sale 2024 finished successfully',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'a3',
    type: 'contact',
    title: 'New contact added',
    description: 'John Smith was added to your contacts',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'a4',
    type: 'template',
    title: 'Template approved',
    description: 'feedback_request template is now active',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'a5',
    type: 'campaign',
    title: 'Campaign started',
    description: 'Product Launch campaign is now running',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
  },
];
